name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: yarn install
    - run: yarn dist
    - run: sudo apt-get install xvfb
    - run: xvfb-run --auto-servernum yarn test
      env:
        CI: true
