name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - run: yarn install
    - run: yarn dist
    - run: yarn test
      env:
        CI: true
